class OrderStatus:
    OPEN = "open"
    COMPLETE = "complete"
    OPEN_PENDING = "open_pending"
    VALIDATION_PENDING = "validation_pending"
    PUT_ORDER_REQ_RECEIVED = "put_order_req_received"
    TRIGGER_PENDING = "trigger_pending"
    REJECTED = "rejected"
    CANCELLED = "cancelled"
    CREATED = "created"
    FAILED = "failed"
